version: '3.8'

services:
  db:
    image: postgres
    env_file: '.env'
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 20

  api:
    image: api:latest
    env_file: '.env'
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "app/main.py"]

networks:
  default:
    name: service_network